export enum CardioRespiratorySystem {
    NORMAL = 'NORMAL',
    BREATHING_DIFFICULTY = 'DIFICULDADE RESPIRATÓRIA',
    COUGH = 'TOSSE',
    NASAL_CONGESTION = 'CONGESTÃO NASAL',
    OTHER = 'OUTRO',
}
