export enum LocomotorSystem {
    NORMAL = 'NORMAL',
    PAIN = 'DOR',
    STIFFNESS = 'RIGIDEZ',
    SWELLING = 'INCHAÇO',
    DIFFICULTY = 'DIFICULDADE',
    POSTURAL_CHANGES = 'ALTERAÇÕES POSTURAIS',
    FRACTURES = 'FRATURAS',
    OTHER = 'OUTRO',
}
