export enum UrogenitalSystem {
    NORMAL = 'NORMAL',
    DIFFICULTY_URINATING = 'DIFFICULTY_URINATING',
    BLOOD_IN_URINE = 'BLOOD_IN_URINE',
    INCONTINENCE = 'INCONTINENCE',
    OTHER = 'OTHER',
}
