export enum UrogenitalSystem {
    NORMAL = 'NORMAL',
    DIFFICULTY_URINATING = 'DIFICULDADE AO URINAR',
    BLOOD_IN_URINE = 'SANGUE NA URINA',
    INCONTINENCE = 'INCONTINÊNCIA',
    OTHER = 'OUTRO',
}
